'use client';

import { CalendarBlank, FileText, ChartLineUp, ShieldWarning, ArrowsClockwise, Flame } from '@phosphor-icons/react';

const featuresData = [
  { icon: <CalendarBlank weight="fill" />, title: "AI Personalized Timetable", desc: "Dynamically adjusting schedules based on your speed, syllabus weightage, and remaining days.", bgColor: "bg-icon-blue-bg", fgColor: "text-icon-blue-fg" },
  { icon: <FileText weight="fill" />, title: "AI Generated Tests", desc: "Practice with high-probability questions generated by AI tailored to your current weakness.", bgColor: "bg-icon-purple-bg", fgColor: "text-icon-purple-fg" },
  { icon: <ChartLineUp weight="fill" />, title: "Performance Dashboard", desc: "Visualize your progress with deep insights into topic mastery and time management.", bgColor: "bg-icon-pink-bg", fgColor: "text-icon-pink-fg" },
  { icon: <ShieldWarning weight="fill" />, title: "Mistake Analysis", desc: "AI categorizes your errors (conceptual, silly, or time-out) so you know exactly where to improve.", bgColor: "bg-icon-red-bg", fgColor: "text-icon-red-fg" },
  { icon: <ArrowsClockwise weight="fill" />, title: "Smart Revision Planner", desc: "Automated spaced repetition alerts for topics you're starting to forget.", bgColor: "bg-icon-orange-bg", fgColor: "text-icon-orange-fg" },
  { icon: <Flame weight="fill" />, title: "Study Streak Tracking", desc: "Gamified progress tracking to keep you consistent and motivated throughout your prep journey.", bgColor: "bg-icon-yellow-bg", fgColor: "text-icon-yellow-fg" },
];

const Features = () => {
  return (
    <section id="features" className="py-32 bg-bg">
      <div className="container">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-[2.25rem] font-extrabold text-text-dark mb-4 tracking-tight">Study Smarter, Not Harder</h2>
          <p className="text-lg text-text-muted">Everything you need to crack your next competitive exam.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {featuresData.map((feature, idx) => (
            <div key={idx} className="bg-surface border border-gray-200 rounded-2xl p-8 shadow-sm hover:-translate-y-1 hover:shadow-xl transition-all duration-300">
              <div className={`w-12 h-12 rounded-lg flex items-center justify-center text-2xl mb-6 ${feature.bgColor} ${feature.fgColor}`}>{feature.icon}</div>
              <h3 className="text-lg font-bold text-text-dark mb-3">{feature.title}</h3>
              <p className="text-[15px] text-text-muted leading-relaxed">{feature.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
